[server]
enableCORS = true
enableXsrfProtection = true

[theme]
# Ajouter des couleurs personnalis√©es
# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"
# font="sans serif"